#Minecraft server properties
server-port=25565
level-name=world
allow-nether=true
spawn-protection=0
max-players=10
spawn-animals=true
online-mode=false
enable-rcon=false
level-seed=
pvp=true
difficulty=3
gamemode=0
max-tick-time=60000
spawn-monsters=true
generate-structures=true
view-distance=10
white-list=false
allow-flight=false
server-ip=
